import { IProduct, Product } from '../models/Product';

type SeedProduct = Omit<IProduct, 'createdAt' | 'updatedAt'>;

const products: SeedProduct[] = [
  {
    slug: 'crafty-cat-whiskers',
    name: 'Whiskers the Calico Kitten',
    productType: 'Dolls',
    designTheme: 'Domestic Animals',
    yarnType: 'Velvet Chenille',
    size: 'Medium (23 cm)',
    price: 34.99,
    originalPrice: 42,
    rating: 4.9,
    reviewCount: 128,
    stockCount: 6,
    prepTimeDays: 2,
    isBestSeller: true,
    isNew: false,
    description: 'Whiskers is a cuddly calico kitten handcrafted with plush velvet chenille yarn. Features tiny pink paw pads, embroidered whiskers, and a cozy hand-stitched bell collar.',
    highlights: [
      '100% Ultra-Soft Velvet Chenille Yarn',
      'Safety-locked glass eyes & soft hypoallergenic stuffing',
      'Hand-embroidered facial expression (no hard plastic edges)',
      'Includes custom birth tag & care pouch',
    ],
    careInstructions: 'Spot clean gently with cold water and mild soap. Air dry in natural shade.',
    images: [],
    isActive: true,
  },
  {
    slug: 'carrot-carl',
    name: 'Carl the Cheerful Carrot',
    productType: 'Dolls',
    designTheme: 'Vegetables',
    yarnType: 'Milk Cotton',
    size: 'Medium (23 cm)',
    price: 24.99,
    originalPrice: 29.99,
    rating: 4.8,
    reviewCount: 94,
    stockCount: 12,
    prepTimeDays: 1,
    isBestSeller: true,
    isNew: false,
    description: 'Carl is a vibrant orange carrot with a fluffy green leafy sprout hair. Crafted from durable milk cotton for crisp stitch definition and endless hugs.',
    highlights: [
      'Bright non-fading milk cotton yarn',
      'Flexible green stem leaves',
      'Stuffed with premium recycled polyester fiberfill',
      'Ideal nursery or desk decoration',
    ],
    careInstructions: 'Hand wash in cool water. Reshape while damp.',
    images: [],
    isActive: true,
  },
  {
    slug: 'sammy-strawberry',
    name: 'Sammy the Sweet Strawberry',
    productType: 'Bag Charms',
    designTheme: 'Fruits',
    yarnType: 'Velvet Chenille',
    size: 'Mini (10 cm)',
    price: 18.5,
    rating: 5,
    reviewCount: 82,
    stockCount: 3,
    prepTimeDays: 2,
    isBestSeller: true,
    isNew: true,
    description: 'Sammy is a pocket-sized strawberry plush with hand-stitched seed speckles and a leafy green crown topper. Ultra plush and squishy!',
    highlights: [
      'Pocket miniature size — fits right in your palm',
      'Hand-embroidered white seeds',
      'Optional keychain loop included upon request',
      'Gift box included',
    ],
    careInstructions: 'Spot clean only.',
    images: [],
    isActive: true,
  },
  {
    slug: 'barnaby-bear',
    name: 'Barnaby Honey Bear',
    productType: 'Dolls',
    designTheme: 'Wild Animals',
    yarnType: 'Chunky Wool',
    size: 'Giant (38 cm)',
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.9,
    reviewCount: 156,
    stockCount: 4,
    prepTimeDays: 4,
    isBestSeller: true,
    isNew: false,
    description: 'Barnaby is a big, huggable teddy bear crocheted with heavy chunky wool yarn. Dressed in a cute removable knitted scarf.',
    highlights: [
      'Heavy chunky yarn for substantial cuddly weight',
      'Removable knitted plaid scarf',
      'Safety jointed arms and legs',
      'Crafted with 100% natural wool blend',
    ],
    careInstructions: 'Gentle hand wash in wool detergent. Lay flat to dry.',
    images: [],
    isActive: true,
  },
  {
    slug: 'sparkle-unicorn',
    name: 'Sparkle Star Unicorn',
    productType: 'Dolls',
    designTheme: 'Fantasy',
    yarnType: 'Velvet Chenille',
    size: 'Medium (23 cm)',
    price: 38,
    rating: 4.9,
    reviewCount: 110,
    stockCount: 8,
    prepTimeDays: 3,
    isBestSeller: false,
    isNew: true,
    description: 'Sparkle features a golden metallic yarn horn, pastel rainbow mane curls, and star embroidery on her hip. Magical dreams guaranteed!',
    highlights: [
      'Shimmering metallic gold horn detail',
      'Individual hand-curled rainbow mane strands',
      'Super soft plush velvet body',
      'Perfect magical keepsake',
    ],
    careInstructions: 'Spot clean gently with damp cloth.',
    images: [],
    isActive: true,
  },
  {
    slug: 'sunny-sunflower',
    name: 'Sunny the Pot Sunflower',
    productType: 'Flower Pots',
    designTheme: 'Flowers',
    yarnType: 'Milk Cotton',
    size: 'Medium (23 cm)',
    price: 29.5,
    originalPrice: 34,
    rating: 4.7,
    reviewCount: 64,
    stockCount: 10,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: false,
    description: 'A potted crochet sunflower that never wilts! Sitting in a warm terra-cotta yarn pot with a bright happy smile.',
    highlights: [
      'Weighted base so it stands upright independently',
      '12 handcrafted golden petals',
      'No watering ever needed!',
      'Brightens any workspace or windowsill',
    ],
    careInstructions: 'Dust with soft dry brush.',
    images: [],
    isActive: true,
  },
  {
    slug: 'avocado-alex',
    name: 'Alex the Cozy Avocado',
    productType: 'Dolls',
    designTheme: 'Fruits',
    yarnType: 'Organic Bamboo',
    size: 'Medium (23 cm)',
    price: 27.99,
    rating: 4.8,
    reviewCount: 78,
    stockCount: 7,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: false,
    description: 'Alex has a soft brown plush pit belly, fuzzy green outer skin, and rosy pink cheeks. A fan favorite for foodies and plant lovers.',
    highlights: [
      'Eco-friendly Organic Bamboo Cotton yarn',
      'Extremely smooth skin touch texture',
      'Blush cheek embroidery',
      'Stuffed with recycled hypoallergenic polyfill',
    ],
    careInstructions: 'Machine washable on cold gentle cycle in laundry bag.',
    images: [],
    isActive: true,
  },
  {
    slug: 'pocket-penguin',
    name: 'Pippin the Pocket Penguin',
    productType: 'Keychains',
    designTheme: 'Aquatic Animals',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 16.99,
    rating: 5,
    reviewCount: 91,
    stockCount: 15,
    prepTimeDays: 1,
    isBestSeller: true,
    isNew: false,
    description: 'Pippin is a tiny chubby penguin wearing a mini yellow winter beanie! Compact enough to accompany you on all your daily adventures.',
    highlights: [
      'Includes tiny removable beanie hat',
      'Keyring loop ready',
      'Extra sturdy tight-gauge crochet weave',
      'Instant mood booster',
    ],
    careInstructions: 'Spot clean only.',
    images: [],
    isActive: true,
  },
  {
    slug: 'broccie-bob',
    name: 'Broccie the Happy Broccoli',
    productType: 'Dolls',
    designTheme: 'Vegetables',
    yarnType: 'Velvet Chenille',
    size: 'Medium (23 cm)',
    price: 26,
    rating: 4.6,
    reviewCount: 45,
    stockCount: 9,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: false,
    description: 'Broccie features textured french-knot florets that are delightfully tactile to touch. Makes eating greens fun!',
    highlights: [
      'Textured floret stitches for sensory delight',
      'Soft velvet stalk handle',
      'Embroidered friendly grin',
      'Great gift for chefs and kids',
    ],
    careInstructions: 'Spot clean gently.',
    images: [],
    isActive: true,
  },
  {
    slug: 'daisy-rose',
    name: 'Rosie the Velvet Rose Pot',
    productType: 'Flower Pots',
    designTheme: 'Flowers',
    yarnType: 'Velvet Chenille',
    size: 'Medium (23 cm)',
    price: 32.5,
    rating: 4.9,
    reviewCount: 88,
    stockCount: 5,
    prepTimeDays: 3,
    isBestSeller: false,
    isNew: true,
    description: 'An elegant romantic red velvet rose in a plush cream pot. The perfect anniversary, Valentine, or birthday gift that lasts forever.',
    highlights: [
      'Soft deep-crimson velvet petals',
      'Hand-stitched green stem leaves',
      'Weighted base stays upright',
      'Comes with customizable gift card tag',
    ],
    careInstructions: 'Dust with clean dry cloth.',
    images: [],
    isActive: true,
  },
  {
    slug: 'puff-dragon',
    name: 'Puff the Baby Mint Dragon',
    productType: 'Dolls',
    designTheme: 'Fantasy',
    yarnType: 'Milk Cotton',
    size: 'Giant (38 cm)',
    price: 54.99,
    originalPrice: 65,
    rating: 4.95,
    reviewCount: 142,
    stockCount: 3,
    prepTimeDays: 5,
    isBestSeller: true,
    isNew: false,
    description: 'Puff is a gentle mint green baby dragon with lilac felt wings, soft belly ridges, and tiny embroidered snout nostrils.',
    highlights: [
      'Intricate multi-part assembly with wings & tail',
      'Giant cuddle size',
      'Pastel color scheme',
      'Collector edition CraftyWrap certificate',
    ],
    careInstructions: 'Hand wash cold with wool wash. Air dry.',
    images: [],
    isActive: true,
  },
  {
    slug: 'bella-bunny',
    name: 'Bella Lavender Bunny',
    productType: 'Dolls',
    designTheme: 'Domestic Animals',
    yarnType: 'Organic Bamboo',
    size: 'Medium (23 cm)',
    price: 31.99,
    rating: 4.85,
    reviewCount: 67,
    stockCount: 8,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: true,
    description: 'Bella features extra-long floppy bunny ears lined with floral cotton fabric, and a fluffy pom-pom tail.',
    highlights: [
      'Floppy 7-inch long bunny ears',
      'Fabric ear lining accents',
      'Fluffy handmade yarn pom-pom tail',
      'All-natural organic bamboo yarn',
    ],
    careInstructions: 'Hand wash cool, dry flat.',
    images: [],
    isActive: true,
  },
  {
    slug: 'buzzy-bee-keychain',
    name: 'Buzzy Bee Crochet Keychain',
    productType: 'Keychains',
    designTheme: 'Insects',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 14.99,
    rating: 4.9,
    reviewCount: 52,
    stockCount: 18,
    prepTimeDays: 1,
    isBestSeller: true,
    isNew: false,
    description: 'A charming honeybee keychain with translucent yarn wings and tiny antennas. Keeps your keys safe and sweet!',
    highlights: ['Sturdy brass keyring loop', 'Hand-stitched stripes', 'Lightweight & durable'],
    careInstructions: 'Spot clean with soapy damp cloth.',
    images: [],
    isActive: true,
  },
  {
    slug: 'octopus-towel-hanger',
    name: 'Ollie Octopus Towel Hanger',
    productType: 'Towel Hanging',
    designTheme: 'Aquatic Animals',
    yarnType: 'Milk Cotton',
    size: 'Medium (23 cm)',
    price: 28.5,
    rating: 4.8,
    reviewCount: 39,
    stockCount: 10,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: false,
    description: 'A practical kitchen or bathroom towel holder shaped like a friendly ocean octopus with curly tentacles.',
    highlights: ['Includes wooden ring for towel support', '8 curly tentacles', 'Moisture-resistant yarn blend'],
    careInstructions: 'Machine wash cool gentle cycle.',
    images: [],
    isActive: true,
  },
  {
    slug: 'daisy-tote-bag',
    name: 'Granny Square Daisy Hand Bag',
    productType: 'Hand Bags',
    designTheme: 'Flowers',
    yarnType: 'Organic Bamboo',
    size: 'Giant (38 cm)',
    price: 1200,
    originalPrice: 1400,
    rating: 4.95,
    reviewCount: 73,
    stockCount: 5,
    prepTimeDays: 4,
    isBestSeller: true,
    isNew: false,
    description: 'Handcrafted bohemian tote bag featuring 12 vintage daisy granny squares and sturdy woven straps.',
    highlights: ['Lined interior with phone pocket', 'Soft organic bamboo cotton', 'Comfortable double shoulder straps'],
    careInstructions: 'Hand wash cool, reshape and dry flat.',
    images: [],
    isActive: true,
  },
  {
    slug: 'sunflower-door-screen',
    name: 'Sunflower Garland Door Screen',
    productType: 'Door Screens',
    designTheme: 'Flowers',
    yarnType: 'Milk Cotton',
    size: 'Giant (38 cm)',
    price: 58,
    rating: 4.9,
    reviewCount: 28,
    stockCount: 4,
    prepTimeDays: 5,
    isBestSeller: false,
    isNew: true,
    description: 'Decorative hanging doorway screen adorned with 9 crocheted sunflowers and cascading vine leaves.',
    highlights: ['Includes wooden hanging rod', 'Hand-knotted macrame vine cords', 'Warm entryway decor'],
    careInstructions: 'Gently shake or dust with clean cloth.',
    images: [],
    isActive: true,
  },
  {
    slug: 'cherry-bag-charm',
    name: 'Sweet Twin Cherry Bag Charm',
    productType: 'Bag Charms',
    designTheme: 'Fruits',
    yarnType: 'Velvet Chenille',
    size: 'Mini (10 cm)',
    price: 16.5,
    rating: 4.85,
    reviewCount: 61,
    stockCount: 14,
    prepTimeDays: 1,
    isBestSeller: false,
    isNew: false,
    description: 'A pop of sweet color for your backpack or purse! Two plump red velvet cherries on a green stem with golden clip.',
    highlights: ['Gold alloy swivel snap hook', 'Ultra-plush velvet texture', 'Great gift item'],
    careInstructions: 'Spot clean gently.',
    images: [],
    isActive: true,
  },
  {
    slug: 'frog-mug-mat',
    name: 'Frankie Frog Coffee Coaster Mat',
    productType: 'Mats',
    designTheme: 'Domestic Animals',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 12.99,
    rating: 4.75,
    reviewCount: 42,
    stockCount: 20,
    prepTimeDays: 1,
    isBestSeller: false,
    isNew: false,
    description: 'A cute absorbent green frog face coaster mat to keep your desk free of coffee rings.',
    highlights: ['Heat-resistant & highly absorbent', 'Non-slip flat weave', 'Dishwasher safe'],
    careInstructions: 'Hand or machine wash cool.',
    images: [],
    isActive: true,
  },
  {
    slug: 'cactus-pencil-stand',
    name: 'Sprout Cactus Desk Pencil Stand',
    productType: 'Pencil Stands',
    designTheme: 'Vegetables',
    yarnType: 'Milk Cotton',
    size: 'Medium (23 cm)',
    price: 25.99,
    rating: 4.9,
    reviewCount: 48,
    stockCount: 7,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: true,
    description: 'Organize your pens in style with this adorable crocheted Saguaro cactus holder pot!',
    highlights: ['Holds 10+ pens and pencils', 'Sturdy reinforced inner cup', 'Decorative pink cactus flower tip'],
    careInstructions: 'Spot clean only.',
    images: [],
    isActive: true,
  },
  {
    slug: 'butterfly-wall-hanging',
    name: 'Monarch Butterfly Wall Tapestry',
    productType: 'Wall Hanging',
    designTheme: 'Insects',
    yarnType: 'Organic Bamboo',
    size: 'Medium (23 cm)',
    price: 36,
    rating: 4.8,
    reviewCount: 31,
    stockCount: 6,
    prepTimeDays: 3,
    isBestSeller: false,
    isNew: false,
    description: 'Vibrant orange and black monarch butterfly woven tapestry with soft tassel fringes.',
    highlights: ['Natural driftwood hanging stick', 'Intricate wing details', 'Boho nursery decoration'],
    careInstructions: 'Comb tassels gently with wide tooth comb.',
    images: [],
    isActive: true,
  },
  {
    slug: 'bear-beanie-cap',
    name: 'Cozy Bear Ear Crochet Cap',
    productType: 'Caps',
    designTheme: 'Wild Animals',
    yarnType: 'Chunky Wool',
    size: 'Medium (23 cm)',
    price: 29.99,
    rating: 4.9,
    reviewCount: 84,
    stockCount: 11,
    prepTimeDays: 2,
    isBestSeller: true,
    isNew: false,
    description: 'Warm and adorable beanie featuring 3D handcrafted teddy bear ears. Available in versatile warm beige.',
    highlights: ['Super stretchy comfortable fit', 'Soft non-itchy wool blend', 'Double layered warmth'],
    careInstructions: 'Hand wash cool with wool detergent.',
    images: [],
    isActive: true,
  },
  {
    slug: 'pastel-rose-bouquet',
    name: 'Forever Pastel Rose Yarn Bouquet',
    productType: 'Bouquets',
    designTheme: 'Flowers',
    yarnType: 'Milk Cotton',
    size: 'Giant (38 cm)',
    price: 49.99,
    originalPrice: 58,
    rating: 5,
    reviewCount: 112,
    stockCount: 6,
    prepTimeDays: 4,
    isBestSeller: true,
    isNew: false,
    description: 'A breathtaking bouquet of 6 hand-crocheted roses wrapped in Korean craft paper and satin ribbon.',
    highlights: ['Includes 6 long-stemmed roses & baby breath stems', 'Ready for gifting with luxury wrap', 'Will never wilt'],
    careInstructions: 'Keep in dry area out of direct sunlight.',
    images: [],
    isActive: true,
  },
  {
    slug: 'ladybug-head-clip',
    name: 'Lucky Ladybug Hair Clip Pair',
    productType: 'Head Clips',
    designTheme: 'Insects',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 11.5,
    rating: 4.85,
    reviewCount: 36,
    stockCount: 16,
    prepTimeDays: 1,
    isBestSeller: false,
    isNew: false,
    description: 'Set of two cheerful red and black ladybug hair snaps lined with gentle alligator clips.',
    highlights: ['No-snag felt backing', 'Secure grip for all hair types', 'Set of 2 included'],
    careInstructions: 'Spot clean gently.',
    images: [],
    isActive: true,
  },
  {
    slug: 'lemon-coasters-set',
    name: 'Zesty Lemon Slice Coaster Set',
    productType: 'Coasters',
    designTheme: 'Fruits',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 19.99,
    rating: 4.9,
    reviewCount: 57,
    stockCount: 12,
    prepTimeDays: 2,
    isBestSeller: false,
    isNew: false,
    description: 'Set of 4 bright yellow citrus slice coasters crafted with absorbent high-gauge cotton yarn.',
    highlights: ['Includes set of 4 coasters', 'Protect wooden surfaces from condensation', 'Bright summer vibe'],
    careInstructions: 'Machine washable.',
    images: [],
    isActive: true,
  },
  {
    slug: 'tulip-hair-band',
    name: 'Blooming Tulip Crochet Hairband',
    productType: 'Hair Bands',
    designTheme: 'Flowers',
    yarnType: 'Organic Bamboo',
    size: 'Mini (10 cm)',
    price: 15.99,
    rating: 4.8,
    reviewCount: 29,
    stockCount: 14,
    prepTimeDays: 1,
    isBestSeller: false,
    isNew: true,
    description: 'Soft flexible headband decorated with 3 miniature 3D tulip buds in pastel pink and yellow.',
    highlights: ['Comfortable elastic band, non-pinching', 'Ultra-soft bamboo yarn', 'Hand-stitched flowers'],
    careInstructions: 'Gentle hand wash cold.',
    images: [],
    isActive: true,
  },
  {
    slug: 'toadstool-pencil-toppers',
    name: 'Toadstool Magic Pencil Toppers',
    productType: 'Pencil Toppers',
    designTheme: 'Fantasy',
    yarnType: 'Milk Cotton',
    size: 'Mini (10 cm)',
    price: 9.99,
    rating: 4.7,
    reviewCount: 44,
    stockCount: 25,
    prepTimeDays: 1,
    isBestSeller: false,
    isNew: false,
    description: 'Pack of 3 cute red mushroom cap pencil toppers. Fits standard #2 pencils and pens!',
    highlights: ['Includes 3 mushroom toppers', 'Fits pencils, pens, and stylus tips', 'Fun back-to-school accessory'],
    careInstructions: 'Spot clean as needed.',
    images: [],
    isActive: true,
  },
];

export async function seedProducts(): Promise<void> {
  await Promise.all(
    products.map(async (product) => {
      const { originalPrice, ...productWithoutOriginalPrice } = product;
      const update = originalPrice === undefined
        ? { $set: productWithoutOriginalPrice, $unset: { originalPrice: '' } }
        : { $set: product };

      await Product.findOneAndUpdate(
        { slug: product.slug },
        update,
        { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true },
      );
    }),
  );
}
